from maya import cmds

def main():
    cmds.menu(l = 'scriptsInTools', p ='MayaWindow', to = True)

    cmds.menuItem( subMenu=True, label='ExternalScript', to = True)
    cmds.menuItem( label='ModelChecker', c = 'from externalScript.modelChecker.src import modelChecker as ps; reload(ps); ps.main()')
    cmds.menuItem( label='ErrorCheckingTool', c = 'from externalScript.errorCheckingTool import ErrorCheckingTool as ps; reload(ps); ps.StartUI()')
    cmds.menuItem( label='SkinningTool', c = 'from externalScript.skinningTool import SkinningToolsUI as ps; reload(ps); ps.startUI()' )
    cmds.setParent( '..', menu=True )

    cmds.menuItem( divider = True, dividerLabel = 'Modeling')
    cmds.menuItem( label='autoRename', c = 'from scriptsInTools.MayaExecute import getNameSplits_autoRename as ps; reload(ps); ps.main()')
    cmds.menuItem( label='GeometryReset', c = 'from scriptsInTools.singleRun import freezeResetHisDel as ps; reload(ps); ps.main()')

    cmds.menuItem( subMenu=True, label='CreateObjects', to = True)
    cmds.menuItem( label='Cube', i = 'polyCube.png', c = 'from scriptsInTools.MayaExecute import createNodes_polyCube as ps; reload(ps); ps.main()')
    cmds.menuItem( label='Ball',  i = 'polySphere.png', c = 'from scriptsInTools.MayaExecute import createNodes_polyBall as ps; reload(ps); ps.main()')
    cmds.menuItem( label='Cylinder', i = 'polyCylinder.png', c = 'from scriptsInTools.MayaExecute import createNodes_polyCylinder as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Plean', i = 'polyMesh.png', c = 'from scriptsInTools.MayaExecute import createNodes_polyPlane as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='ImagePlean', i = 'ImagePlane.png', c = 'from scriptsInTools.MayaExecute import createNodes_imagePlane as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Camera', i = 'view.png', c = 'from scriptsInTools.MayaExecute import createNodes_camera as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='AmbientLight', i = 'ambientlight.png', c = 'from scriptsInTools.MayaExecute import createNodes_ambientLight as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='DirectionalLight', i = 'directionallight.png', c = 'from scriptsInTools.MayaExecute import createNodes_directionalLight as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='PointLight', i = 'pointlight.png', c = 'from scriptsInTools.MayaExecute import createNodes_pointLight as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='SpotLight',  i = 'spotlight.png', c = 'from scriptsInTools.MayaExecute import createNodes_spotLight as ps; reload(ps); ps.main()' )
    cmds.setParent( '..', menu=True )

    cmds.menuItem( subMenu=True, label='ModelingEdit', to = True)
    cmds.menuItem( label='CornerEdge', i = 'cornerEdge.png', c = 'from scriptsInTools.singleRun import cornerEdgeSelect as ps; reload(ps); ps.main()')
    cmds.menuItem( label='Combine', i = 'polyUnite.png', c = 'from scriptsInTools.singleRun import combineMesh as ps; reload(ps); ps.main()')
    cmds.menuItem( label='Extract' , i = 'polyChipOff.png', c = 'from scriptsInTools.singleRun import extractComponent as ps; reload(ps); ps.main()')
    cmds.menuItem( label='HardEdge', i = 'polyHardEdge.png', c = 'from scriptsInTools.singleRun import hardEdge as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='SoftEdge', i = 'polySoftEdge.png', c = 'from scriptsInTools.singleRun import softEdge as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='CamImageOffConnect', c = 'from scriptsInTools.singleRun import camImageOffsetConnection as ps; reload(ps); ps.main()' )
    cmds.setParent( '..', menu=True )

    cmds.menuItem( divider = True, dividerLabel = 'Rigging')
    
    cmds.menuItem( subMenu=True, label='setCurves', to = True)
    cmds.menuItem( label='Antenna', c = 'from scriptsInTools.MayaExecute import setCurves_antenna as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Arrow1', c = 'from scriptsInTools.MayaExecute import setCurves_arrow1 as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Arrow2', c = 'from scriptsInTools.MayaExecute import setCurves_arrow2 as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Arrow4', c = 'from scriptsInTools.MayaExecute import setCurves_arrow4 as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Circle', c = 'from scriptsInTools.MayaExecute import setCurves_circle as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Cube', c = 'from scriptsInTools.MayaExecute import setCurves_cube as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Hexagon', c = 'from scriptsInTools.MayaExecute import setCurves_hexagon as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Pyramid', c = 'from scriptsInTools.MayaExecute import setCurves_pyramid as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Square', c = 'from scriptsInTools.MayaExecute import setCurves_square as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='Twist', c = 'from scriptsInTools.MayaExecute import setCurves_twist as ps; reload(ps); ps.main()' )
    cmds.menuItem( label='VectorIK', c = 'from scriptsInTools.MayaExecute import setCurves_vectorIK as ps; reload(ps); ps.main()' )
    cmds.setParent( '..', menu=True )

    cmds.menuItem( subMenu=True, label='CurveEdit', to = True)
    cmds.menuItem( label='CurveInSelects', c = 'from scriptsInTools.singleRun import curveInSelect as ps; reload(ps); ps.main()')
    cmds.setParent( '..', menu=True )

    cmds.menuItem( subMenu=True, label='ColorChenge', to = True)
    cmds.menuItem( label='CtrlColorChange', c = 'from scriptsInTools.singleRun import ctrlColorChenge as ps; reload(ps); ps.main()')
    cmds.menuItem( label='CtrlColorFreeChange', c = 'from scriptsInTools.singleRun import ctrlColorFreeChenge as ps; reload(ps); ps.main()')
    cmds.setParent( '..', menu=True )

    cmds.menuItem( subMenu=True, label='Skin', to = True)
    cmds.menuItem( label='SkinPaintValue', i = 'skinPaintValue.png', c = 'from scriptsInTools.singleRun import skinPaintValue as ps; reload(ps); ps.main()' )
    cmds.setParent( '..', menu=True )

    cmds.menuItem( divider = True, dividerLabel = 'Other')
    cmds.menuItem( subMenu=True, label='SelectsEdit', to = True )
    cmds.menuItem( label='JointRadiusEdit', c = 'from scriptsInTools.singleRun import jointRadius as ps; reload(ps); ps.main()')
    cmds.menuItem( optionBox=True, c = 'from scriptsInTools.singleRun import jointRadius as ps; reload(ps); ps.option()')
    cmds.setParent( '..', menu=True )

    cmds.menuItem( subMenu=True, label='Inquiry', to = True)
    cmds.menuItem( label='LookNodeType', c = 'from scriptsInTools.singleRun import lookNodeType as ps; reload(ps); ps.main()')
    cmds.menuItem( label='LookSelectList', c = 'from scriptsInTools.singleRun import lookSelectList as ps; reload(ps); ps.main()')
    cmds.menuItem( label='LookSelectKeyAttr', c = 'from scriptsInTools.singleRun import lookSelectKeyAttr as ps; reload(ps); ps.main()')
    cmds.menuItem( label='LookBindJoints', c = 'from scriptsInTools.singleRun import lookBindJoints as ps; reload(ps); ps.main()')
    cmds.menuItem( label='LookShapeColor', c = 'from scriptsInTools.singleRun import lookShapeColor as ps; reload(ps); ps.main()')
    cmds.menuItem( label='LookMatrix', c = 'from scriptsInTools.singleRun import lookMatrix as ps; reload(ps); ps.main()')
    cmds.setParent( '..', menu=True )
